### ISSUE TITLE
A request to make it compatible with V2 scheduler.

### ISSUE THREAD

**Issue by adix03** [ijgnd/anki__scheduler_apply_different_ease_basic#1]

**Comment by ijgnd** [comment]
the version on github should work with V2. Replace the contents of the `__init__.py` in your add-on folder with the contents of the file from this repo. 

I haven't tested it so it's not published on ankiweb. If it works for you let me know. Then I can publish it on ankiweb for other people.

**Comment by adix03** [comment]
Finally, I made the switch to V2 scheduler and the add-on is working fine. It's been 4 days. I think you can publish it.
